CREATE TABLE IF NOT EXISTS "User" (
  "id" VARCHAR(255) PRIMARY KEY DEFAULT (cuid()),
  "clerkId" VARCHAR(255) UNIQUE NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Document" (
  "id" VARCHAR(255) PRIMARY KEY DEFAULT (cuid()),
  "userId" VARCHAR(255) NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "filename" VARCHAR(255) NOT NULL,
  "fileType" VARCHAR(50) NOT NULL,
  "qdrantCollection" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Conversation" (
  "id" VARCHAR(255) PRIMARY KEY DEFAULT (cuid()),
  "userId" VARCHAR(255) NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Message" (
  "id" VARCHAR(255) PRIMARY KEY DEFAULT (cuid()),
  "conversationId" VARCHAR(255) NOT NULL REFERENCES "Conversation"("id") ON DELETE CASCADE,
  "role" VARCHAR(50) NOT NULL,
  "content" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "Document_userId_idx" ON "Document"("userId");
CREATE INDEX IF NOT EXISTS "Conversation_userId_idx" ON "Conversation"("userId");
CREATE INDEX IF NOT EXISTS "Message_conversationId_idx" ON "Message"("conversationId");
